version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 3005:3000
    environment:
      - NEXT_APP_API_BASE_URL=http://localhost:4005
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    environment:
      - PORT=4005
    ports:
      - 4005:4005